=== meghamohadikar/BE/services-with-Camel10/sx-order-specification/src/main/resources/schemas/body/common/sx-order-session.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "funcResultCode": { "type": "string" },
        "id": {
            "format": "int32",
            "type": "integer"
        },
        "status": {
            "enum": [ "DRAFT", "SENT", "SEND_ERROR", "DW_OPEN", "DW_CANCEL", "SX_FAILED", "SX_CONFIRM", "SX_TIMEOUT", "SPLITTED", "EXECUTE_READY", "ARCHIVED" ],
            "type": "string"
        },
        "auditInformations": {
            "$ref": "audit-informations.json"
        },
        "instruments": {
            "type": "array",
            "items": {
                "$ref": "instrument.json"
            }
        },
        "portfolios": {
            "type": "array",
            "items": {
                "$ref": "portfolio.json"
            }
        },
        "instructionDetails": {
            "type": "array",
            "items": {
                "$ref": "instruction-details.json"
            }
        },
        "owner": {
            "$ref": "user.json"
        },
        "reloadDate": {
            "type": "string"
        },
        "transmitDate": {
            "type": "string"
        },
        "orders": {
            "type": "array",
            "items": {
                "$ref": "sx-order.json"
            }
        }
    }
}

=== meghamohadikar/BE/services-with-Camel10/sx-order-specification/src/main/resources/examples/body/common/sx-order-session.json
{
    "auditInformations": {
        "funcResultCode": "string",
        "id": 0,
        "status": "DRAFT",
        "createdBy": {
            "id": "0",
            "fullname": "Jane Doe",
            "trigram": "JDO"
        },
        "creationDate": "2019-05-27T09:05:28.368Z",
        "updatedBy": {
            "id": "0",
            "fullname": "Jane Doe",
            "trigram": "JDO"
        },
        "updateDate": "2019-05-29T09:05:28.368Z"
    },
    "instruments": [
        {
            "isin": "IN1234567890",
            "internalCode": "000000001.00",
            "name": "Instrument 1",
            "type": "Type 1",
            "lastPrice": {
                "currency": "CHF",
                "price": 13594.58,
                "date": "2019-05-27T09:05:28.368Z"
            },
            "productRiskClassification": "string",
            "preferedInvestmentUniverse": "string",
            "discretionaryInvestmentUniverse": "string"
        }
    ],
    "portfolios": [
        {
            "company": "001",
            "number": "000001212345",
            "code": "001.000001212345",
            "label": "Portfolio 1",
            "navInReferenceCurrency": 400,
            "navInBookingCenterCurrency": 10,
            "referenceCurrency": "CHF",
            "managementType": "SUIV",
            "carp": {
                "id": 0,
                "name": "string",
                "code": "string",
                "denomination": "string"
            },
            "investmentProfile": "NONE",
            "servicingCenter": "string",
            "riskProfile": {
                "id": 0,
                "name": "string",
                "code": "string",
                "denomination": "string"
            },
            "serviceLevel": "NONE",
            "relationshipManager": {
                "id": 5,
                "name": "Relationship Manager Name",
                "code": "RMN",
                "denomination": "Relationship Manager Denomination"
            },
            "categoryRM": "NO_GROUPING",
            "portfolioManager": {
                "id": 0,
                "name": "string",
                "code": "string",
                "denomination": "string"
            },
            "taxationProfilePM": {
                "id": 0,
                "name": "string",
                "code": "string",
                "denomination": "string"
            },
            "unit": "string",
            "pme": "string",
            "externalPortfolioManager": {
                "id": 0,
                "name": "string",
                "code": "string",
                "denomination": "string"
            },
            "finderManager": {
                "id": 0,
                "name": "string",
                "code": "string",
                "denomination": "string"
            },
            "bookingCenter": "string",
            "feesPolicy": "string",
            "companyNature": {
                "id": 0,
                "name": "string",
                "code": "string",
                "denomination": "string"
            },
            "creationDate": "2019-05-27T09:05:28.368Z",
            "closingDate": "2019-05-27T09:05:28.368Z",
            "averagePRC": 38,
            "mifidCategory": {
                "id": 0,
                "name": "string",
                "code": "string",
                "denomination": "string"
            },
            "mifidProtectionLevel": {
                "id": 0,
                "name": "string",
                "code": "string",
                "denomination": "string"
            },
            "priiPsInScope": true,
            "fidlegInScope": true,
            "fidlegCategory": "string",
            "cisaInScope": true,
            "qualifiedInvestor": true,
            "clientType": {
                "id": 0,
                "name": "string",
                "code": "string",
                "denomination": "string"
            },
            "dutyToDisclose": "string",
            "taxConformityStatus": "CONF_OUT_OF_SCOPE",
            "luganoConvention": "string",
            "usTaxStatus": "string",
            "usTaxPool": "QI_POOL_000",
            "submittedToFATCA": "F_NON_US",
            "crsStatus": {
                "id": 0,
                "name": "string",
                "code": "string",
                "denomination": "string"
            },
            "traspasoEnabled": true,
            "taxationProfile": "string",
            "cashAccounts": [
                {
                    "code": "001.6638685",
                    "subType": "COMPTE COURANT",
                    "incomeAccount": true,
                    "currency": "EUR",
                    "description": "Cash Account 1",
                    "balance": 50006913.45,
                    "accountedBalance": 0,
                    "portfolioCode": "001.000001212345"
                }
            ],
            "participants": [
                {
                    "code": "JDO",
                    "id": 0,
                    "portfolioCode": "001.000001212345",
                    "company": "001",
                    "portfolioNumber": "000001212345",
                    "lastName": "DOE",
                    "firstName": "Jane",
                    "birthdate": "2019-01-01T09:05:28.369Z",
                    "hasSignaturePower": true,
                    "homeCountry": "Switzerland",
                    "personType": "PP",
                    "roles": [
                        "string"
                    ],
                    "signature": "COLL2",
                    "isRepresentative": false,
                    "mifidCategory": "Retail",
                    "knowledgeLevel": 0.25,
                    "experienceLevel": 0.25,
                    "knowledgesAndExperiences": {
                        "experiences": {
                            "_0500": true,
                            "_1000": true,
                            "_3000": false,
                            "_3010": false,
                            "_3030": false,
                            "_3500": false,
                            "_7500": false,
                            "_7505": true,
                            "_7506": false,
                            "_9000": false,
                            "_9030": false,
                            "_9035": false,
                            "_9090": false,
                            "_9100": false
                        },
                        "knowledges": {
                            "_0500": false,
                            "_1000": true,
                            "_3000": false,
                            "_3010": false,
                            "_3030": false,
                            "_3500": false,
                            "_7500": false,
                            "_7505": false,
                            "_7506": false,
                            "_9000": false,
                            "_9030": false,
                            "_9035": false,
                            "_9090": true,
                            "_9100": true
                        },
                        "optups": {
                            "_0500": null,
                            "_1000": null,
                            "_3000": null,
                            "_3010": null,
                            "_3030": null,
                            "_3500": null,
                            "_7500": null,
                            "_7505": null,
                            "_7506": null,
                            "_9000": null,
                            "_9030": null,
                            "_9035": null,
                            "_9090": null,
                            "_9100": null
                        }
                    }
                }
            ],
            "custody": "string"
        }
    ],
    "instructionDetails": [
        {
            "portfolio": {
                "company": "001",
                "number": "000001212345",
                "code": "001.000001212345",
                "label": "Portfolio 1",
                "navInReferenceCurrency": 400,
                "navInBookingCenterCurrency": 10,
                "referenceCurrency": "CHF",
                "managementType": "SUIV",
                "carp": {
                    "id": 0,
                    "name": "string",
                    "code": "string",
                    "denomination": "string"
                },
                "investmentProfile": "NONE",
                "servicingCenter": "string",
                "riskProfile": {
                    "id": 0,
                    "name": "string",
                    "code": "string",
                    "denomination": "string"
                },
                "serviceLevel": "NONE",
                "relationshipManager": {
                    "id": 5,
                    "name": "Relationship Manager Name",
                    "code": "RMN",
                    "denomination": "Relationship Manager Denomination"
                },
                "categoryRM": "NO_GROUPING",
                "portfolioManager": {
                    "id": 0,
                    "name": "string",
                    "code": "string",
                    "denomination": "string"
                },
                "taxationProfilePM": {
                    "id": 0,
                    "name": "string",
                    "code": "string",
                    "denomination": "string"
                },
                "unit": "string",
                "pme": "string",
                "externalPortfolioManager": {
                    "id": 0,
                    "name": "string",
                    "code": "string",
                    "denomination": "string"
                },
                "finderManager": {
                    "id": 0,
                    "name": "string",
