=== meghamohadikar/BE/services-with-Camel10/sx-order-specification/src/main/resources/schemas/body/responses/sx-order-init-post.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "actions": {
            "type": "array",
            "items": {
                "$ref": "../common/order-action.json"
            }
        },
        "orderNatures": {
            "type": "array",
            "items": {
                "$ref": "../common/id-name.json"
            }
        },
        "orderTypes": {
            "type": "array",
            "items": {
                "$ref": "../common/id-name.json"
            }
        },
        "instrumentOperationTypes": {
            "type": "array",
            "items": {
                "$ref": "../common/id-name.json"
            }
        },
        "instrumentExchangePlaces": {
            "type": "array",
            "items": {
                "$ref": "../common/id-name.json"
            }
        },
        "instrumentDividendPolicies": {
            "type": "array",
            "items": {
                "$ref": "../common/id-name.json"
            }
        },
        "discountFees": {
            "type": "array",
            "items": {
                "$ref": "../common/id-name.json"
            }
        },
        "depositaries": {
            "type": "array",
            "items": {
                "$ref": "../common/id-name.json"
            }
        },
        "currencies": {
            "type": "array",
            "items": {
                "$ref": "../common/id-name.json"
            }
        },
        "dealers": {
            "type": "array",
            "items": {
                "$ref": "../common/id-name.json"
            }
        },
        "sxOrder": {
            "$ref": "../common/sx-order.json"
        },
        "responseMessages": {
            "type": "array",
            "items": {
                "$ref": "../common/result-message.json"
            }
        }
    }
}

=== meghamohadikar/BE/services-with-Camel10/sx-order-specification/src/main/resources/examples/body/responses/sx-order-init-post.json
{
    "actions": [
        {
            "isBuyAction": true,
            "id": "1",
            "name": "Buy Qty"
        }
    ],
    "orderNatures": [
        {
            "id": "SP",
            "name": "SPOT"
        }
    ],
    "orderTypes": [
        {
            "id": "N",
            "name": "Standard"
        }
    ],
    "instrumentOperationTypes": [
        {
            "id": "PCH",
            "name": "Purchase"
        }
    ],
    "instrumentExchangePlaces": [
        {
            "id": "067",
            "name": "NASDAQ"
        }
    ],
    "instrumentDividendPolicies": [
        {
            "id": "1",
            "name": "Cash"
        }
    ],
    "discountFees": [
        {
            "id": "1",
            "name": "0"
        }
    ],
    "depositaries": [
        {
            "id": "209834",
            "name": "CITIBANK N.A. 0%  (209834)"
        }
    ],
    "sxOrder": {
        "orderSessionId": 123456,
        "warnings": [
            {}
        ],
        "auditInformations": {
            "funcResultCode": "string",
            "id": 0,
            "status": "DRAFT",
            "createdBy": {
                "id": "0",
                "fullname": "Jane Doe",
                "trigram": "JDO"
            },
            "creationDate": "2019-05-27T09:05:28.369Z",
            "updatedBy": {
                "id": "0",
                "fullname": "Jane Doe",
                "trigram": "JDO"
            },
            "updateDate": "2019-05-27T09:05:28.369Z"
        },
        "code": "string",
        "currency": "string",
        "feesMethod": "string",
        "depositary": {
            "id": 0,
            "name": "string",
            "code": "string",
            "denomination": "string"
        },
        "operationNumber": "string",
        "externalId": 0,
        "operationNature": "Sell",
        "action": "BuyQuantity",
        "traspasoAction": "StepIn",
        "orderNature": "SP",
        "orderType": "Standard",
        "operationType": "NONE",
        "marketPlace": "string",
        "dividendPolicy": "string",
        "dealerRemark": "string",
        "dealer": "string",
        "dealerPrice": {
            "currency": "string",
            "value": 0,
            "date": "2019-05-27T09:05:28.369Z"
        },
        "limitPrice": {
            "currency": "string",
            "value": 0,
            "date": "2019-05-27T09:05:28.369Z"
        },
        "costsAndCharges": [
            {}
        ],
        "dealNumber": "string",
        "fenicsDealNumber": "string",
        "contractNumber": "string",
        "lastPrice": {
            "currency": "string",
            "value": 0,
            "date": "2019-05-27T09:05:28.369Z"
        },
        "instrumentCode": "string",
        "ordersDetails": [
            {
                "orderId": 123456,
                "client": {
                    "portfolioCode": "string",
                    "cashAccountCode": "string"
                },
                "externalId": 0,
                "objective": 0,
                "pendingsOrderCount": 0,
                "calculatedQuantity": 0,
                "accountedQuantity": 0,
                "accountingDate": "2019-05-27T09:05:28.369Z",
                "valueDate": "2019-05-27T09:05:28.369Z",
                "roundLotForced": 0,
                "operationNetAmount": 0,
                "navPercentageBefore": 0,
                "navPercentageAfter": 0,
                "quantityBefore": 0,
                "quantityAfter": 0,
                "sequenceNumber": "string",
                "accruedInterest": 0,
                "action": "BuyQuantity",
                "traspasoAction": "StepIn",
                "costsAndCharges": [
                    {}
                ],
                "warnings": [
                    {
                        "caseId": "1",
                        "messageCode": "Capgemini - Sell - 200",
                        "description": "Credit Request",
                        "type": "Type 1",
                        "category": "Category 1",
                        "warningNature": "Strategy",
                        "warningSubNature": "Warning sub-nature 1",
                        "severity": "Severity 1",
                        "orderId": "1",
                        "orderSessionId": "123456",
                        "portfolioId": "001.000001234567",
                        "instrumentId": "001723456.00",
                        "clarificationType": "text",
                        "clarificationText": "User comment",
                        "clarificationStatus": "Clarification status 1"
                    }
                ],
                "auditInformations": {
                    "funcResultCode": "string",
                    "id": 0,
                    "status": "DRAFT",
                    "createdBy": {
                        "id": "0",
                        "fullname": "Jane Doe",
                        "trigram": "JDO"
                    },
                    "creationDate": "2019-05-27T09:05:28.369Z",
                    "updatedBy": {
                        "id": "0",
                        "fullname": "Jane Doe",
                        "trigram": "JDO"
                    },
                    "updateDate": "2019-05-27T09:05:28.369Z"
                }
            }
        ]
    },
    "responseMessages": [
        {
            "message": "string"
        }
    ]
}
